### ISSUE TITLE
Issue in SessionController file

### ISSUE THREAD

**Issue by vik0803** [gamerwalt/TodoMultitenantDemo#1]
seems that there is an issue in sessioncontroller file before line 58

once the records are entered in db, users are still needed to be created at mysql whereas we just go next step with establishing connection with users that are still not created at mysql level

**Comment by gamerwalt** [comment]
Are you using 1 mysql instances? And do you have the databases setup already?

Anyway you can send me the log? Will have to take a look at it.

**Comment by gamerwalt** [comment]
Did you have this figured out. Note that the user in the env file needs to have DBA privileges.
