### ISSUE TITLE
Please supply the necessary identifiers to resolve your tenant database

### ISSUE THREAD

**Issue by ImmanuelJL** [gamerwalt/TodoMultitenantDemo#2]
Dear, may i know why i get this message "TenantDatabaseException in TenantConnector.php line 19:
Please supply the necessary identifiers to resolve your tenant database" i have no idea what is going on. Did i miss something? Thanks

**Comment by gamerwalt** [comment]
Check your config.

**Comment by gamerwalt** [comment]
Can you send me exactly the Exception in your log file?

**Comment by gamerwalt** [comment]
Hope you found the issue.

**Comment by ImmanuelJL** [comment]
Iyups, i just make a wrong configuration. Its works perfectly fine
